# Generated by Django 6.0.7 on 2026-09-10 18:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_order_payment_review_resolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('provider_type', models.CharField(choices=[('ride_hailing', 'Ride Hailing / App'), ('bus_coach', 'Bus / Coach'), ('matatu_shuttle', 'Matatu / Shuttle'), ('personal_rider', 'Personal Rider'), ('shop_fleet', 'Shop Rider / Fleet'), ('courier', 'Courier Company'), ('other', 'Other')], default='other', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_type', models.CharField(choices=[('internal', 'Shop Managed'), ('external', 'External Provider')], db_index=True, default='external', max_length=20)),
                ('method', models.CharField(choices=[('local_door', 'Local Door Delivery'), ('long_distance', 'Long Distance Delivery'), ('station_pickup', 'Station / Parcel Office Pickup'), ('store_pickup', 'Store Pickup'), ('personal_rider', 'Personal Rider / Bike'), ('other', 'Other')], default='local_door', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('ready_for_collection', 'Ready for Collection'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('failed', 'Delivery Attempt Failed'), ('returned', 'Returned'), ('cancelled', 'Delivery Cancelled')], db_index=True, default='pending', max_length=30)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('destination', models.CharField(max_length=255)),
                ('pickup_point', models.CharField(blank=True, max_length=255)),
                ('transport_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_phone', models.CharField(blank=True, max_length=30)),
                ('customer_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='orders.order')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='delivery.deliveryprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('successful', 'Successful'), ('customer_unavailable', 'Customer Unavailable'), ('unreachable', 'Customer Unreachable'), ('wrong_address', 'Wrong Address'), ('transport_delay', 'Transport Delay'), ('parcel_not_collected', 'Parcel Not Collected'), ('other', 'Other')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts_created', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='delivery.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('ready_for_collection', 'Ready for Collection'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('failed', 'Delivery Attempt Failed'), ('returned', 'Returned'), ('cancelled', 'Delivery Cancelled')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events_created', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
