# Generated by Django 6.0.7 on 2026-09-11 07:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('town', models.CharField(blank=True, db_index=True, max_length=150)),
                ('method', models.CharField(choices=[('local_door', 'Local Door Delivery'), ('long_distance', 'Long Distance Delivery'), ('station_pickup', 'Station / Parcel Office Pickup'), ('store_pickup', 'Store Pickup'), ('personal_rider', 'Personal Rider / Bike'), ('other', 'Other')], default='local_door', max_length=30)),
                ('pickup_point', models.CharField(blank=True, max_length=255)),
                ('pricing_mode', models.CharField(choices=[('fixed', 'Fixed Delivery Fee'), ('confirm', 'Fee Confirmed After Order')], default='fixed', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estimated_time', models.CharField(blank=True, help_text='Example: Same day, 1-2 days, Next day.', max_length=120)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='delivery.deliveryprovider')),
            ],
            options={
                'ordering': ['county', 'town', 'method'],
            },
        ),
    ]
