# Generated by Django 6.0.7 on 2026-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='free_delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orders at or above this subtotal receive free delivery for this zone.', max_digits=12, null=True),
        ),
    ]
