# Generated by Django 6.0.7 on 2026-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='Optional company or business registration number.', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='checkout_closed_message',
            field=models.CharField(blank=True, default='', help_text='Optional message shown when online ordering is disabled.', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='credit_note_prefix',
            field=models.CharField(default='CN', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='receipt_prefix',
            field=models.CharField(default='RCP', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='tax_pin',
            field=models.CharField(blank=True, help_text='Optional tax/KRA PIN shown on business documents.', max_length=100),
        ),
    ]
