# Generated by Django 6.0.7 on 2026-09-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storesettings_business_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='credit_note_prefix',
            field=models.CharField(blank=True, default='CN', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='receipt_prefix',
            field=models.CharField(blank=True, default='RCP', max_length=20),
        ),
    ]
