# Generated by Django 6.0.7 on 2026-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_variant_orderitem_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('consumed', 'Consumed')], default='reserved', max_length=20),
        ),
    ]
