# Generated by Django 6.0.7 on 2026-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
