# Generated by Django 6.0.7 on 2026-09-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryzone'),
        ('orders', '0012_order_payment_review_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pricing_status',
            field=models.CharField(choices=[('fixed', 'Fixed Delivery Price'), ('quote_pending', 'Delivery Quote Pending'), ('quoted', 'Delivery Quote Confirmed')], db_index=True, default='fixed', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryzone'),
        ),
    ]
