# Generated by Django 6.0.7 on 2026-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_delivery_pricing_status_order_delivery_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_quote_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
