# Generated by Django 6.0.7 on 2026-09-11 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderdocument'),
        ('payments', '0004_refundrequest_processed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, max_length=140, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_count', models.PositiveIntegerField(default=0)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='orders.order')),
                ('refund_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='payments.refundrequest')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
