# Generated by Django 6.0.7 on 2026-09-11 22:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_creditnotedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_code_at_checkout',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_symbol_at_checkout',
            field=models.CharField(default='KSh', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='minimum_order_amount_at_checkout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_enabled_at_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate_at_checkout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
