# Generated by Django 6.0.7 on 2026-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=190, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_message',
            field=models.TextField(blank=True),
        ),
    ]
