# Generated by Django 6.0.7 on 2026-09-11 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_event_key_notification_sms_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('orders', 'Order Updates'), ('payments', 'Payment Updates'), ('delivery', 'Delivery Updates'), ('returns', 'Returns & Refunds'), ('marketing', 'Marketing')], db_index=True, default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('payment_updates', models.BooleanField(default=True)),
                ('delivery_updates', models.BooleanField(default=True)),
                ('return_refund_updates', models.BooleanField(default=True)),
                ('marketing_email', models.BooleanField(default=False)),
                ('marketing_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
